import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Providers } from "./providers";
import { LoadingProvider } from "@/components/Loading/LoadingContexts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GitHub To Do",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased min-h-screen flex flex-col">
        <AntdRegistry>
          <LoadingProvider> {/* Add LoadingProvider here */}
            <Providers>{children}</Providers>
          </LoadingProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
